#!/bin/bash
# alias to composer locally installed command: phpspec

# imported functions
# get composer installed php function
function getComposerInstalledCommand()
{
    local cmd="$1"

    if [ -e "./bin/$1" ]; then
        echo "./bin/$1"
    elif  [ -e "./vendor/bin/$1" ]; then
        echo "./vendor/bin/$1"
    else
        echo ""
    fi
}

# run composer installed php function
function runComposerInstalledCommand()
{
    local cmd="$1"
    shift

    php "${cmd}" $@

    exit $?
}
# end imported functions

CMD_NAME="phpspec"
CMD=$(getComposerInstalledCommand "${CMD_NAME}")

if [ -z "${CMD}" ]; then
    echo "ERROR: Composer locally installed command '${CMD_NAME}' not found."
    exit 1
fi

runComposerInstalledCommand "${CMD}" $@
